### ISSUE TITLE
The scrolling/jumping issue

### ISSUE THREAD

**Issue by datamaunz** [CT-Generator/ct-gen#52]
Problem:

Certainly on mobile, each subsequent screen is not shown from the top when you load it, but already scrolled down to the point where you were on the previous screen. The effect is that one might not realize what the steps you are one through are, because one starts reading mid-page. 
When you click on one of the options, the screen scrolls/jumps to the top option (even if you click the bottom option).

Solution

Clicking “Next” brings you to top of next page
Clicking an option scrolls to that option
Include a message that says ‘scroll down for details’ whenever you click an option (definitely on mobile), so that people don’t miss the description

**Comment by thrasher995** [comment]
The app focuses on content when selecting any of the images, no issue here. Closed
